Repository TheOpenInnovator/Zen-Note, pull requests merged in 2024-10, with the labels that each got.

#8 improving responsiveness
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024

#9 Enhancement of the Alert Messages: Added SweetAlert2 Library as alert box
  index.html
  script.js
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#2 added edit feature to entries
  script.js
  style.css
Labels: hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#19 fix: line breaks when typing in the input
  script.js
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#13 Fixes #12 by enhancing the UI of the Web Application
  index.html
  script.js
  style.css
Labels: enhancement, good first issue, hacktoberfest, HacktoberFest2024

#24 Old and New Merge
  script.js
Labels: hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#27 Added update functionality
  script.js
Labels: bug, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#25 Fixes #20 by adding favicons for different screen sizes
  images/logo.png
  index.html
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#32 fix: line break of entries
  script.js
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#31 Enhance the Styling of the Snapshot #10
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted, A1

#34 Issue #30 - fixed login and signup form elements
  login.html
  signup.html
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted

#36 added category to note
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted, A1

#40 Fixes #39 - Fixed the issue where the text remained black in dark mode
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted, A3

#41 [ui] enhanced the navbar
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted, A3

#42 Share snapshot on socials
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted
